export const ALL_COMPANYS = 'ALL_COMPANYS'
export const ALL_COMPANYS_SUCCESS = 'ALL_COMPANYS_SUCCESS'
export const ALL_COMPANYS_FAILURE = 'ALL_COMPANYS_FAILURE'

export const COMPANY_BY_ID = 'COMPANY_BY_ID'
export const COMPANY_BY_ID_SUCCESS = 'COMPANY_BY_ID_SUCCESS'

export const ADD_COMPANY = 'ADD_COMPANY'
export const ADD_COMPANY_SUCCESS = 'ADD_COMPANY_SUCCESS'
export const ADD_COMPANY_FAILURE = 'ADD_COMPANY_FAILURE'

export const UPDATE_COMPANY = 'UPDATE_COMPANY'
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS'
export const UPDATE_COMPANY_FAILURE = 'UPDATE_COMPANY_FAILURE'

export const REMOVE_COMPANY = 'REMOVE_COMPANY'
export const REMOVE_COMPANY_SUCCESS = 'REMOVE_COMPANY_SUCCESS'
export const REMOVE_COMPANY_FAILURE = 'REMOVE_COMPANY_FAILURE'

// export const ADD_TO_CART = 'ADD_TO_CART'
// export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const ALL_PRODUCTS = 'ALL_PRODUCTS'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_BY_COMPANY_ID = 'ALL_PRODUCTS_BY_COMPANY_ID'
export const ALL_PRODUCTS_BY_COMPANY_ID_SUCCESS = 'ALL_PRODUCTS_BY_COMPANY_ID_SUCCESS'



export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'

